--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: detalles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalles (
    id bigint NOT NULL,
    fecha_ingreso timestamp(6) without time zone,
    hora_ingreso time(6) without time zone,
    id_reparacion bigint,
    monto_reparacion integer NOT NULL,
    patente character varying(255)
);


ALTER TABLE public.detalles OWNER TO postgres;

--
-- Name: detalles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: detalles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detalles (id, fecha_ingreso, hora_ingreso, id_reparacion, monto_reparacion, patente) FROM stdin;
1	2023-07-15 00:00:00	11:00:00	1	120000	ABCD12
2	2023-11-15 00:00:00	11:30:00	2	130000	DEFZ45
3	2023-12-20 00:00:00	13:45:00	3	350000	GHIG89
4	2024-01-25 00:00:00	10:15:00	4	300000	DKLH12
5	2024-02-28 00:00:00	09:30:00	5	250000	MNOJ45
6	2024-03-15 00:00:00	10:00:00	6	100000	PQRX78
7	2024-04-10 00:00:00	08:30:00	7	100000	STUC01
8	2015-05-20 00:00:00	14:45:00	8	180000	VWXV34
9	2023-06-15 00:00:00	11:00:00	9	180000	YZAB67
10	2020-07-05 00:00:00	08:00:00	10	130000	BCDN90
11	2019-08-10 00:00:00	09:15:00	11	80000	ASGC41
12	2022-09-15 00:00:00	10:45:00	2	130000	ABCD12
13	2022-10-20 00:00:00	12:00:00	4	210000	DEFZ45
14	2023-11-25 00:00:00	08:30:00	3	350000	GHIG89
15	2023-12-28 00:00:00	09:00:00	1	180000	DKLH12
16	2024-01-10 00:00:00	10:30:00	5	250000	MNOJ45
17	2023-02-15 00:00:00	08:45:00	9	150000	PQRX78
18	2024-03-20 00:00:00	15:00:00	7	100000	STUC01
19	2023-04-15 00:00:00	11:15:00	8	180000	VWXV34
20	2022-05-05 00:00:00	08:30:00	1	180000	YZAB67
21	2021-06-10 00:00:00	09:45:00	10	130000	BCDN90
22	2024-04-11 20:00:00	12:00:00	10	150000	SAFW13
\.


--
-- Name: detalles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalles_id_seq', 22, true);


--
-- Name: detalles detalles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles
    ADD CONSTRAINT detalles_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

