--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: historial; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.historial (
    id bigint NOT NULL,
    costo_total real NOT NULL,
    descuentos real NOT NULL,
    fecha_ingreso timestamp(6) without time zone,
    fecha_recogida timestamp(6) without time zone,
    fecha_salida timestamp(6) without time zone,
    hora_ingreso time(6) without time zone,
    hora_recogida time(6) without time zone,
    hora_salida time(6) without time zone,
    iva real NOT NULL,
    monto_total_reparaciones real NOT NULL,
    patente character varying(255),
    recargos real NOT NULL
);


ALTER TABLE public.historial OWNER TO postgres;

--
-- Name: historial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.historial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: historial; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.historial (id, costo_total, descuentos, fecha_ingreso, fecha_recogida, fecha_salida, hora_ingreso, hora_recogida, hora_salida, iva, monto_total_reparaciones, patente, recargos) FROM stdin;
1	618800	40000	2023-11-15 00:00:00	2023-11-17 00:00:00	2023-11-16 00:00:00	11:30:00	09:00:00	12:45:00	98800	500000	ABCD12	60000
2	618800	40000	2023-12-20 00:00:00	2023-12-22 00:00:00	2023-12-21 00:00:00	13:45:00	13:30:00	14:30:00	98800	500000	MNOJ45	60000
\.


--
-- Name: historial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.historial_id_seq', 2, true);


--
-- Name: historial historial_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.historial
    ADD CONSTRAINT historial_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

