--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: precios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.precios (
    id bigint NOT NULL,
    id_reparacion bigint,
    precio integer NOT NULL,
    tipo_de_motor character varying(255)
);


ALTER TABLE public.precios OWNER TO postgres;

--
-- Name: precios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.precios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.precios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: precios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.precios (id, id_reparacion, precio, tipo_de_motor) FROM stdin;
1	1	120000	Gasolina
2	1	120000	Diésel
3	1	180000	Híbrido
4	1	220000	Eléctrico
5	2	130000	Gasolina
6	2	130000	Diésel
7	2	190000	Híbrido
8	2	230000	Eléctrico
9	3	350000	Gasolina
10	3	450000	Diésel
11	3	700000	Híbrido
12	3	800000	Eléctrico
13	4	210000	Gasolina
14	4	210000	Diésel
15	4	300000	Híbrido
16	4	300000	Eléctrico
17	5	150000	Gasolina
18	5	150000	Diésel
19	5	200000	Híbrido
20	5	250000	Eléctrico
21	6	100000	Gasolina
22	6	120000	Diésel
23	6	450000	Híbrido
24	6	0	Eléctrico
25	7	100000	Gasolina
26	7	100000	Diésel
27	7	100000	Híbrido
28	7	100000	Eléctrico
29	8	180000	Gasolina
30	8	180000	Diésel
31	8	210000	Híbrido
32	8	250000	Eléctrico
33	9	150000	Gasolina
34	9	150000	Diésel
35	9	180000	Híbrido
36	9	180000	Eléctrico
37	10	130000	Gasolina
38	10	140000	Diésel
39	10	220000	Híbrido
40	10	0	Eléctrico
41	11	80000	Gasolina
42	11	80000	Diésel
43	11	80000	Híbrido
44	11	80000	Eléctrico
\.


--
-- Name: precios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.precios_id_seq', 44, true);


--
-- Name: precios precios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.precios
    ADD CONSTRAINT precios_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

