--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: vehiculos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vehiculos (
    id bigint NOT NULL,
    anio integer NOT NULL,
    kilometraje real NOT NULL,
    marca character varying(255),
    modelo character varying(255),
    patente character varying(255),
    tipo_motor character varying(255),
    tipo_vehiculo character varying(255)
);


ALTER TABLE public.vehiculos OWNER TO postgres;

--
-- Name: vehiculos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vehiculos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehiculos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: vehiculos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.vehiculos (id, anio, kilometraje, marca, modelo, patente, tipo_motor, tipo_vehiculo) FROM stdin;
1	2018	50000	Toyota	Corolla	ABCD12	Gasolina	Sedán
2	2017	6000	Ford	Focus	DEFZ45	Diésel	Hatchback
3	2019	40000	Chevrolet	Cruze	GHIG89	Gasolina	Sedán
4	2020	30000	Honda	Civic	DKLH12	Híbrido	Sedán
5	2019	20000	Volkswagen	Golf	MNOJ45	Eléctrico	Hatchback
6	2024	15000	Hyundai	Tucson	PQRX78	Gasolina	SUV
7	2019	80000	Nissan	Frontier	STUC01	Diésel	Pickup
8	2020	700	Mercedes-Benz	Sprinter	VWXV34	Diésel	Furgoneta
9	2021	10000	BMW	X5	YZAB67	Híbrido	SUV
10	2019	35000	Audi	A4	BCDN90	Gasolina	Sedán
11	2023	5000	Chevrolet	Whatsapp	ASGC41	Gasolina	Sedán
12	2023	12440	Whatsapp	2	ASFC31	Eléctrico	Furgoneta
13	2024	0	Marca Nueva	Modelo nuevo	SADC12	Gasolina	SUV
14	2024	1234	Marca test	Modelo test	TEST12	Gasolina	SUV
\.


--
-- Name: vehiculos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vehiculos_id_seq', 14, true);


--
-- Name: vehiculos vehiculos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehiculos
    ADD CONSTRAINT vehiculos_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

