--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: descuentos_cantidad_reparacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.descuentos_cantidad_reparacion (
    id bigint NOT NULL,
    cantidad_reparaciones_max integer NOT NULL,
    cantidad_reparaciones_min integer NOT NULL,
    descuento_por_numero_reparaciones real NOT NULL,
    tipo_motor character varying(255)
);


ALTER TABLE public.descuentos_cantidad_reparacion OWNER TO postgres;

--
-- Name: descuentos_cantidad_reparacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.descuentos_cantidad_reparacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.descuentos_cantidad_reparacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: descuentos_cantidad_reparacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.descuentos_cantidad_reparacion (id, cantidad_reparaciones_max, cantidad_reparaciones_min, descuento_por_numero_reparaciones, tipo_motor) FROM stdin;
1	2	1	0.05	Gasolina
2	2	1	0.07	Diésel
3	2	1	0.1	Híbrido
4	2	1	0.08	Eléctrico
5	5	3	0.1	Gasolina
6	5	3	0.12	Diésel
7	5	3	0.15	Híbrido
8	5	3	0.13	Eléctrico
9	9	6	0.15	Gasolina
10	9	6	0.17	Diésel
11	9	6	0.2	Híbrido
12	9	6	0.18	Eléctrico
13	999	10	0.2	Gasolina
14	999	10	0.22	Diésel
15	999	10	0.25	Híbrido
16	999	10	0.23	Eléctrico
\.


--
-- Name: descuentos_cantidad_reparacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.descuentos_cantidad_reparacion_id_seq', 16, true);


--
-- Name: descuentos_cantidad_reparacion descuentos_cantidad_reparacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.descuentos_cantidad_reparacion
    ADD CONSTRAINT descuentos_cantidad_reparacion_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

