--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: descuentos_bonos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.descuentos_bonos (
    id bigint NOT NULL,
    cantidad_descuentos integer NOT NULL,
    marca_vehiculo character varying(255),
    monto_descuentos integer NOT NULL
);


ALTER TABLE public.descuentos_bonos OWNER TO postgres;

--
-- Name: descuentos_bonos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.descuentos_bonos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.descuentos_bonos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: descuentos_bonos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.descuentos_bonos (id, cantidad_descuentos, marca_vehiculo, monto_descuentos) FROM stdin;
1	3	Toyota	70000
2	2	Ford	50000
3	1	Hyundai	30000
4	7	Honda	40000
\.


--
-- Name: descuentos_bonos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.descuentos_bonos_id_seq', 4, true);


--
-- Name: descuentos_bonos descuentos_bonos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.descuentos_bonos
    ADD CONSTRAINT descuentos_bonos_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

