apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-descuentos-bonos-deployment
  labels:
    app: ms-descuentos-bonos-deployment
spec:
  selector:
    matchLabels:
      app: ms-descuentos-bonos-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-descuentos-bonos-deployment
    spec:
      containers:
        - name: ms-descuentos-bonos
          image: cpalma2001/ms-descuentos-bonos
          ports:
            - containerPort: 8086
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_DESCUENTOSBONOS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_DESCUENTOSBONOS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_DESCUENTOSBONOS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_DESCUENTOSBONOS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_DESCUENTOSBONOS
