apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-descuentos-cantidad-reparaciones-deployment
  labels:
    app: ms-descuentos-cantidad-reparaciones-deployment
spec:
  selector:
    matchLabels:
      app: ms-descuentos-cantidad-reparaciones-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-descuentos-cantidad-reparaciones-deployment
    spec:
      containers:
        - name: ms-descuentos-cantidad-reparaciones
          image: cpalma2001/ms-descuentos-cantidad-reparaciones
          ports:
            - containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_DESCUENTOSCANTIDADREPARACION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_DESCUENTOSCANTIDADREPARACION
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_DESCUENTOSCANTIDADREPARACION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_DESCUENTOSCANTIDADREPARACION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_DESCUENTOSCANTIDADREPARACION
