apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-historial-deployment
  labels:
    app: ms-historial-deployment
spec:
  selector:
    matchLabels:
      app: ms-historial-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-historial-deployment
    spec:
      containers:
        - name: ms-historial
          image: cpalma2001/ms-historial
          ports:
            - containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_HISTORIAL
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_HISTORIAL
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_HISTORIAL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_HISTORIAL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_HISTORIAL
