apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-recargos-antiguedad-deployment
  labels:
    app: ms-recargos-antiguedad-deployment
spec:
  selector:
    matchLabels:
      app: ms-recargos-antiguedad-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-recargos-antiguedad-deployment
    spec:
      containers:
        - name: ms-recargos-antiguedad
          image: cpalma2001/ms-recargos-antiguedad
          ports:
            - containerPort: 8089
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_RECARGOSANTIGUEDAD
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_RECARGOSANTIGUEDAD
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_RECARGOSANTIGUEDAD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_RECARGOSANTIGUEDAD
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_RECARGOSANTIGUEDAD
