apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-vehiculo-deployment
  labels:
    app: ms-vehiculo-deployment
spec:
  selector:
    matchLabels:
      app: ms-vehiculo-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-vehiculo-deployment
    spec:
      containers:
        - name: ms-vehiculo
          image: cpalma2001/ms-vehiculo
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_VEHICULOS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_VEHICULOS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_VEHICULOS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_VEHICULOS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_VEHICULOS
