apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  DB_USER_DESCUENTOSBONOS: cG9zdGdyZXM=
  DB_PASSWORD_DESCUENTOSBONOS: cGFzc3dvcmQ=
  DB_USER_DESCUENTOSCANTIDADREPARACION: cG9zdGdyZXM=
  DB_PASSWORD_DESCUENTOSCANTIDADREPARACION: cGFzc3dvcmQ=
  DB_USER_DETALLES: cG9zdGdyZXM=
  DB_PASSWORD_DETALLES: cGFzc3dvcmQ=
  DB_USER_HISTORIAL: cG9zdGdyZXM=
  DB_PASSWORD_HISTORIAL: cGFzc3dvcmQ=
  DB_USER_PRECIOS: cG9zdGdyZXM=
  DB_PASSWORD_PRECIOS: cGFzc3dvcmQ=
  DB_USER_RECARGOSANTIGUEDAD: cG9zdGdyZXM=
  DB_PASSWORD_RECARGOSANTIGUEDAD: cGFzc3dvcmQ=
  DB_USER_RECARGOSKILOMETRAJE: cG9zdGdyZXM=
  DB_PASSWORD_RECARGOSKILOMETRAJE: cGFzc3dvcmQ=
  DB_USER_VEHICULOS: cG9zdGdyZXM=
  DB_PASSWORD_VEHICULOS: cGFzc3dvcmQ=