--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: recargo_antiguedad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recargo_antiguedad (
    id bigint NOT NULL,
    antiguedad_max integer NOT NULL,
    antiguedad_min integer NOT NULL,
    recargo_por_antiguedad real NOT NULL,
    tipo_vehiculo character varying(255)
);


ALTER TABLE public.recargo_antiguedad OWNER TO postgres;

--
-- Name: recargo_antiguedad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recargo_antiguedad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recargo_antiguedad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: recargo_antiguedad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recargo_antiguedad (id, antiguedad_max, antiguedad_min, recargo_por_antiguedad, tipo_vehiculo) FROM stdin;
1	5	0	0	Sedán
2	5	0	0	Hatchback
3	5	0	0	SUV
4	5	0	0	Pickup
5	5	0	0	Furgoneta
6	10	6	0.05	Sedán
7	10	6	0.05	Hatchback
8	10	6	0.07	SUV
9	10	6	0.07	Pickup
10	10	6	0.07	Furgoneta
11	15	11	0.09	Sedán
12	15	11	0.09	Hatchback
13	15	11	0.11	SUV
14	15	11	0.11	Pickup
15	15	11	0.11	Furgoneta
16	999	16	0.15	Sedán
17	999	16	0.15	Hatchback
18	999	16	0.2	SUV
19	999	16	0.2	Pickup
20	999	16	0.2	Furgoneta
\.


--
-- Name: recargo_antiguedad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recargo_antiguedad_id_seq', 20, true);


--
-- Name: recargo_antiguedad recargo_antiguedad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recargo_antiguedad
    ADD CONSTRAINT recargo_antiguedad_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

