--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: recargo_kilometraje; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recargo_kilometraje (
    id bigint NOT NULL,
    kilometraje_max integer NOT NULL,
    kilometraje_min integer NOT NULL,
    recargo_por_kilometraje real NOT NULL,
    tipo_vehiculo character varying(255)
);


ALTER TABLE public.recargo_kilometraje OWNER TO postgres;

--
-- Name: recargo_kilometraje_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recargo_kilometraje ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recargo_kilometraje_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: recargo_kilometraje; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recargo_kilometraje (id, kilometraje_max, kilometraje_min, recargo_por_kilometraje, tipo_vehiculo) FROM stdin;
1	5000	0	0	Sedán
2	5000	0	0	Hatchback
3	5000	0	0	SUV
4	5000	0	0	Pickup
5	5000	0	0	Furgoneta
6	12000	5001	0.03	Sedán
7	12000	5001	0.03	Hatchback
8	12000	5001	0.05	SUV
9	12000	5001	0.05	Pickup
10	12000	5001	0.05	Furgoneta
11	25000	12001	0.07	Sedán
12	25000	12001	0.07	Hatchback
13	25000	12001	0.09	SUV
14	25000	12001	0.09	Pickup
15	25000	12001	0.09	Furgoneta
16	40000	25001	0.12	Sedán
17	40000	25001	0.12	Hatchback
18	40000	25001	0.12	SUV
19	40000	25001	0.12	Pickup
20	40000	25001	0.12	Furgoneta
21	999999	40001	0.2	Sedán
22	999999	40001	0.2	Hatchback
23	999999	40001	0.2	SUV
24	999999	40001	0.2	Pickup
25	999999	40001	0.2	Furgoneta
\.


--
-- Name: recargo_kilometraje_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recargo_kilometraje_id_seq', 25, true);


--
-- Name: recargo_kilometraje recargo_kilometraje_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recargo_kilometraje
    ADD CONSTRAINT recargo_kilometraje_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

